### ISSUE TITLE
The README should caution users against careless instantiation of the client

### ISSUE THREAD

**Issue by orivej** [hashicorp/go-cleanhttp#1]
As explained in [consulapi#1499](https://github.com/hashicorp/consul/pull/1499) and [go-dockerclient#434](https://github.com/fsouza/go-dockerclient/pull/434), it is not safe at all to replace `http.DefaultClient` with `&http.Client{}` or `cleanhttp.DefaultClient()`, and the README should address this fairly obscure and dangerous issue. I think it should suggest library authors to either instantiate a global `DefaultClient`, or to set `DisableKeepAlives` to `true`.

**Comment by jefferai** [comment]
Using a global default client negates the point of this library, which is to ensure that you are using a clean client that will not be modified willy-nilly by other parts of an application. What you're suggesting is simply a different use-case than this library is designed for.

**Comment by orivej** [comment]
`cleanhttp.DefaultClient()` can not replace `http.DefaultClient` due to unbound growth of the number of established connections of many `cleanhttp.DefaultClient()`s in the connection pools of their http transports, and per-library global default client as in https://github.com/hashicorp/consul/pull/1517 currently is the best use of this library.

**Comment by jefferai** [comment]
Let's keep the discussion going at https://github.com/fsouza/go-dockerclient/pull/434
