### ISSUE TITLE
Enable ForceAttemptHTTP2 as default

### ISSUE THREAD

**Issue by kodabb** [hashicorp/go-cleanhttp#17]
Hi,
I'm using cleanhttp through retryablehttp, and one of the site I'm querying is making me upgrade to HTTP2.
However the default implementation of cleanhttp does not let the connection happen, and makes the request return empty data.
I tried to debug this a bit, and it seems that `ForceAttemptHTTP2` is missing from the default options, and by manually setting it to true, the connection happens and data is returned correctly.
This flag has been added to the `http.DefaultTransport`, would it be possible to enable for the default transport options in this package too?
Thanks

**Comment by jefferai** [comment]
I've added this! Will cut a new release now.
