### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by bhourigan** [hashicorp/go-cleanhttp#5]
I get the following errors when attempting to `go install` a project that depends on go-cleanhttp:

```
# github.com/hashicorp/go-cleanhttp
../gocode/src/github.com/hashicorp/go-cleanhttp/cleanhttp.go:27:4: error: unknown field ‘KeepAlive’ in ‘net.Dialer’
    KeepAlive: 30 * time.Second,
    ^
../gocode/src/github.com/hashicorp/go-cleanhttp/cleanhttp.go:29:3: error: unknown field ‘TLSHandshakeTimeout’ in ‘http.Transport’
   TLSHandshakeTimeout: 10 * time.Second,
   ^
```

**Comment by cbednarski** [comment]
@bhourigan These are part of the standard library. What version of `go` are you using?

**Comment by bhourigan** [comment]
you're right - it was a go error on my side. thank you!

**Comment by henti** [comment]
Can you put your resolution here as well. I'm having an issue with "go get github.com/hashicorp/consul/api" for https://github.com/kailunshi/consul-backup and don't have much knowledge on Go.

**Comment by jefferai** [comment]
@henti I don't know if this library is compatible with gccgo, and it's likely that it requires Go 1.5 and higher. Your version of gccgo is probably not new enough with respect to the standard library.
