### ISSUE TITLE
Go 1.7 has more fields set in the default Transport

### ISSUE THREAD

**Issue by glasser** [hashicorp/go-cleanhttp#6]
A few features were added to http.Transport in Go 1.7.  The default transport [now looks like](https://github.com/golang/go/blob/9741d83ceaf046e55077d68719cc2781cd96d5f1/src/net/http/transport.go#L38-L48)

``` go
var DefaultTransport RoundTripper = &Transport{
    Proxy: ProxyFromEnvironment,
    DialContext: (&net.Dialer{
        Timeout:   30 * time.Second,
        KeepAlive: 30 * time.Second,
    }).DialContext,
    MaxIdleConns:          100,
    IdleConnTimeout:       90 * time.Second,
    TLSHandshakeTimeout:   10 * time.Second,
    ExpectContinueTimeout: 1 * time.Second,
}
```

Should these new fields be added? Maybe in a separate file with build tags?

**Comment by jefferai** [comment]
This has been updated!
